Railsチュートリアル第10章
tshiode-aim/rails-tutorial pull request #11
Opened 2019-07-08 08:30 UTC by tshiode-aim

## ストーリー

https://railstutorial.jp/chapters/updating_and_deleting_users?version=5.1#cha-updating_showing_and_deleting_users

## 概要

ユーザーの更新・表示・削除機能を追加しました。

## 画面

・一覧、削除画面
![スクリーンショット 2019-07-08 17 30 17](https://user-images.githubusercontent.com/52316340/60795134-11653800-a1a6-11e9-8fcd-ab1cebf11b40.png)

・更新画面
![スクリーンショット 2019-07-08 17 29 42](https://user-images.githubusercontent.com/52316340/60795089-00b4c200-a1a6-11e9-8e24-8dce44d7e9df.png)

## 仕様・注意事項

変更点
・Herokuデプロイ→手元macで動作確認

## 見どころ

・TODO

2019-07-09 12:04 UTC, ttsuji requested changes
また詳しくは口頭ではなしますー

2019-07-09 12:04 UTC, ttsuji commented on spec/controllers/users_controller_spec.rb
> +    it 'should redirect login page' do
[修正不要]
これを `shared_example` にしてもいいかもですね

2019-07-09 12:04 UTC, ttsuji commented on spec/controllers/users_controller_spec.rb
> +          name: user.name,
[修正不要]
一応変更しようとした事が分かるように一応別の適当な文字列を入れたほうがいいかもですね。

2019-07-09 12:04 UTC, ttsuji commented on spec/factories/user.rb
> +  factory :michael, class: User do
ここは普通にuserでいいと思います。
何のデータがわからなくなるので。

特定のデータを書き換えたいときは `trait` とか使うといいですね。
```ruby
factory :user, class: User do
  name { Faker::Name.name }
  email { Faker::Internet.email }
  password { Faker::Internet.password }
  password_confirmation { password } # これ無理かも
  admin { true }

  trait :michael do
    name { 'Michael Example' }
    email { 'michael_test@example.com' }
  end

  trait :archer do
    name { 'Sterling Archer' }
    email { 'duchess@example.gov' }
  end
end
```

呼び出すときは
```ruby
FactoryBot.build(:user , :michael)
とか
build(:user , :michael)
```

2019-07-09 12:04 UTC, ttsuji commented on spec/integration/users_index_spec.rb
> +  let(:admin) { create(:michael) }
michaelがadminかどうかはわからない情報なので admin: trueを引数に与えたほうがいいですね。
archerも同じです。adminじゃないなら admin: falseを与えておきましょう

2019-07-09 12:04 UTC, ttsuji commented on spec/integration/users_index_spec.rb
> +        is_expected.to have_selector("a[href='#{user_path(user)}']", text: 'delete') unless user == admin
`unless user == admin` これはプログラムコードではなくテストで表現すべきですね。

admin_userのテストとそれ以外をcontextで分けてしまって
admin_userのテストには `削除ボタン` がないことをチェック

逆に通常ユーザには
admin_userのテストには `削除ボタン` があることをチェック

2019-07-10 02:59 UTC, tshiode-aim commented on spec/controllers/users_controller_spec.rb
> +        page.driver.submit :delete, user_path(user), {}
deleteリクエストにはパラメータが不要だったので消しました。

2019-07-10 03:02 UTC, tshiode-aim commented
修正したのでレビューをお願いします。

2019-07-10 04:00 UTC, tshiode-aim commented
口頭でご指摘頂いた箇所を修正しました。レビューをお願いします。

### 指摘頂いた箇所以外の修正

Fakerでunique指定ができるのでやってみました。
https://github.com/tshiode-aim/rails-tutorial/blob/cfc285a4e4729a87da068bc7f546e4fa49bd374e/spec/factories/user.rb#L4

deleteリンクが表示される条件を「管理者以外」だと思ってましたがこれは勘違いで、正しくは「自分以外」でした。そのように修正したらテストにpassしました。
https://github.com/tshiode-aim/rails-tutorial/blob/cfc285a4e4729a87da068bc7f546e4fa49bd374e/spec/integration/users_index_spec.rb#L24-L26

ユーザ変数が admin, non_admin だと中身が想像しにくいので、名称を admin_user, non_admin_user に変更しました。
https://github.com/tshiode-aim/rails-tutorial/blob/cfc285a4e4729a87da068bc7f546e4fa49bd374e/spec/integration/users_index_spec.rb#L7-L8

2019-07-10 05:02 UTC, ttsuji commented on spec/factories/user.rb
> +    email { Faker::Internet.unique.email }
👍

2019-07-10 05:02 UTC, ttsuji approved these changes

2019-07-10 05:04 UTC, merged