Railsチュートリアル第3章
tshiode-aim/rails-tutorial pull request #3
Opened 2019-07-02 08:40 UTC by tshiode-aim

## ストーリー

Railsチュートリアル第3章を実施しました。
https://railstutorial.jp/chapters/static_pages?version=5.1#cha-static_pages

## 概要

ほぼ静的なページの作成、およびminitest、RSpecを用いたテストコードを記述しました。

## 画面

特に載せるものはありません。

## 仕様・注意事項

変更したところ
・第1章と同様にBitbucketの代わりにGitHubを利用しました。

飛ばしたところ
・第1章と同様にHerokuでの動作確認はしておりません。手元のmacで動作確認できたので十分という判断です。

その他
・rubocopでapp/controllers/static_pages_controller.rbにあるメソッドが空であることを指摘されました。暫定措置としてメソッド内にコメントを記載しました。

## 見どころ

・rubocopの設定、およびコードのフォーマットが期待通りになっているかどうか確認してほしいです。
・RSpecの記法に問題がないかどうか確認してほしいです。

2019-07-02 09:49 UTC, ttsuji requested changes

2019-07-02 09:49 UTC, ttsuji commented on config/routes.rb
> +  get 'foo/bar'
多分routingの追加だけじゃなくてcontroller毎作成する演習だと思います。
そこまで難しい内容じゃないので今回は修正不要で

2019-07-02 09:49 UTC, ttsuji commented on app/views/static_pages/help.html.erb
> +</p>
ファイルの末尾は改行を入れましょう。
`app/views/static_pages/home.html.erb` も同じです。

2019-07-02 09:49 UTC, ttsuji commented on spec/controller/static_pages_controller_spec.rb
> +  it 'expect get root' do
どういう時にどういう結果が返ってくるかをテスト表現したいので `context` を追加しましょう。
ついでにテストする対象はどの項目も明確にしておいたほうがいいです。

```
## テストする対象
subject { page }

## どういう状況か
context 'when access to static_pages_home_url' do
  ## 事前にどういうことをしておくか
  before { visit static_pages_home_url }
  ## ほしい結果はなにか
  it 'shoud response code 200' do
    ## テスト内容
  end
end
```

https://qiita.com/kidach1/items/ec184deb106e4e5c90c3
このサイトが詳しいかも

2019-07-02 09:56 UTC, tshiode-aim commented on config/routes.rb
> +  get 'foo/bar'
ご指摘ありがとうございます。controllerも作成してましたがgit addが漏れていたようです。今後気をつけます。

2019-07-02 11:32 UTC, tshiode-aim commented
ご指摘頂いた箇所を修正しました。ご確認をお願いします。

2019-07-03 01:23 UTC, ttsuji requested changes

2019-07-03 01:23 UTC, ttsuji commented on spec/requests/static_pages_spec.rb
> +    it { expect(page).to have_http_status 200 }
`subject` に対するテストは `is_expected.to` が使えます。
よく使うのでこっちで慣れておきましょう。

2019-07-03 01:23 UTC, ttsuji commented on spec/requests/static_pages_spec.rb
> +    it { expect(page).to have_selector('title', text: "Home | #{base_title}", visible: false) }
細かいけどこのテストは何をテストするものかを明記しておきましょう。
テスト内容が人目で判断が効くものなら不要ですが今回はそうではない感じがあります。

```
it 'テストしたい内容を記述' do 
  expect(page).to have_selector('title', text: "Home | #{base_title}", visible: false)
end
```
こんな感じで

2019-07-03 01:23 UTC, ttsuji commented on spec/requests/static_pages_spec.rb
> +    before { visit static_pages_home_url }
これも細かいけど `before` と `it` は若干やってることが異なるので間に改行しておくと読みやすくなります。
beforeは飽くまでも事前準備、 itは検証項目なので。
改行を入れる場所に規約という規約はないですが、なるべく後から見て読みやすいコードっていうのを意識しましょう。

2019-07-03 02:46 UTC, tshiode-aim commented
ご指摘いただいた箇所を修正しました。チェックお願いします。

2019-07-03 04:57 UTC, ttsuji commented on spec/requests/static_pages_spec.rb
> +    it 'should have a word "Home" in the content of the title tag' do
`should have a word "About" in the content of the title tag` ？

ほかも同じように `こうなるべき` という感じのニュアンにしてもらえると嬉しいです。
どんな感じで書いてるかは、プロジェクトコードを読んでみるのも手です。

2019-07-03 05:10 UTC, tshiode-aim commented on spec/requests/static_pages_spec.rb
> +    it 'should have a word "Home" in the content of the title tag' do
ご指摘ありがとうございます。

改めて見ると
`should have a word "About" in the content of the title tag`
だとちょっと煩雑に感じているので、
`should be About page`
にしようと考えています。省略しすぎでしょうか？

2019-07-03 05:13 UTC, ttsuji commented on spec/requests/static_pages_spec.rb
> +    it 'should have a word "Home" in the content of the title tag' do
何を検証してるのかがわかればそれで良いと思います。
ベストは `タイトルに Aboutって入ってるよね` 感じかな。

2019-07-03 05:44 UTC, tshiode-aim commented
修正しましたのでご確認をお願いします。
少し簡略化して
`should have a word "Home" in the title`
にしました。

2019-07-03 05:45 UTC, tshiode-aim commented
ショボい修正をrebaseでまとめたので「静的ページのRSpecをリファクタリング」が新しい変更になってしまいましたが、スルーして頂ければと思います。

2019-07-03 09:38 UTC, ttsuji commented
LGTM

2019-07-03 09:38 UTC, merged