[DNM][WIP] Railsチュートリアル第9章
tshiode-aim/rails-tutorial pull request #9
Opened 2019-07-08 01:58 UTC by tshiode-aim

## ストーリー

https://railstutorial.jp/chapters/advanced_login?version=5.1#cha-advanced_login

## 概要

発展的なログイン機構(Remember me)を追加しました。

## 画面

Remember meチェックボックスを追加しました。
![スクリーンショット 2019-07-08 10 56 25](https://user-images.githubusercontent.com/52316340/60777768-0cd15d00-a16f-11e9-8fa9-6b62358823f5.png)

## 仕様・注意事項

変更点
・Herokuデプロイ→手元macで動作確認

## 見どころ

・TODO

2019-07-09 08:04 UTC, ttsuji requested changes

2019-07-09 08:04 UTC, ttsuji commented on spec/helpers/sessions_helper_spec.rb
> +  subject { current_user }
いきなり subject書いてもこれが何のテストか読み解けないので
```ruby
describe '#current_user' do
  ##テスト内容
end
```
みたいな感じで書きましょう。

ちなみにクラスメソッドの場合は
```ruby
describe '.class_method' do
end
```
で書くと良いです。

http://www.betterspecs.org/jp/
この辺読むといいかも

2019-07-09 08:04 UTC, ttsuji commented on spec/helpers/sessions_helper_spec.rb
> +  before { remember(user) }
[修正不要]

`remember` をここで呼び出すと このテストが `remember` メソッドの挙動に依存してしまうという問題があります。
tutorialに書いてるので修正不要ですがこういうテストはあまり良くない事が多いのです。

この場合は、テスト内容を `remember` メソッドを呼び出したときの `current_user` の挙動という内容でテストを書くなら問題ないかもしれないです。

ただその場合は `remember` メソッドのテストも書いておくのがベストになってきます。

2019-07-09 08:04 UTC, ttsuji commented on spec/integration/users_login_spec.rb
> +  describe 'remembering' do
ここで `describe ` を切るとそれより上のテストはどういうものだったかを明記したほうがわかりやすくなるかもです。

2019-07-09 08:04 UTC, ttsuji commented on spec/support/users_helper.rb
> +  page.driver.submit :delete, logout_path, {}
このlogoutの仕方に違和感がある。
通常のlogout動作を取るなら `click_button 'Log out'` をやるべきかな。
ログアウト後のtopページ遷移状態だとそれを模倣出来ないっていうなら、 `delete logout_path` でそのままリクエスト投げる方が自然な書き方に見える。

2019-07-09 08:04 UTC, ttsuji commented on spec/integration/users_login_spec.rb
> +  describe 'remembering' do
ここのテストは口頭で説明します。

2019-07-09 09:52 UTC, tshiode-aim commented
修正しました。レビューをお願いします。

2019-07-10 05:06 UTC, ttsuji approved these changes

2019-07-10 05:06 UTC, merged